# Generated by Django 5.1.5 on 2025-01-16 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('town', models.CharField(blank=True, max_length=100, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('REPAIR_PROCESS', '4.0 Repair Process'), ('PEOPLE_PROCESSES', '4.4 People Processes'), ('REPAIR_METHODS', '4.5 Repair Methods'), ('EQUIPMENT_TOOLS', '4.6 Equipment & Tools'), ('PARTS_CONSUMABLES', '4.7 Parts & Consumables'), ('REPAIR_TASK_CONTROL', '4.8 Repair Task Control'), ('SUBCONTRACTORS', '4.9 Use of Subcontractors'), ('PROCESS_MANAGEMENT', '5.0 Process Management'), ('CLAIMS_CONFORMITY', '6.0 Claims of Conformity'), ('CUSTOMER_COMPLAINTS', '7.0 Customer Complaints'), ('INTERNAL_AUDIT_REPORTS', 'Internal Audit & Reports')], max_length=50, unique=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/documents/')),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vda.client')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('VDA', 'Vehicle Damage Assessor'), ('PNL', 'Panel Technician'), ('MET', 'Mechanical & Electrical Technician'), ('PNT', 'Paint Technician')], max_length=3)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='vda.client')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('passed_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='vda.job')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='vda.client')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='vda.staff'),
        ),
        migrations.CreateModel(
            name='ToolEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools_equipment', to='vda.client')),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('test_completion_date', models.DateField()),
                ('test_renewal_date', models.DateField()),
                ('test_score', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='vda.client')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='vda.toolequipment')),
            ],
        ),
    ]
