# Generated by Django 5.1.5 on 2025-01-18 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='job',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='client',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
