# Generated by Django 5.1.5 on 2025-01-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vda', '0002_remove_qualification_job_remove_staff_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolequipment',
            name='client',
        ),
        migrations.DeleteModel(
            name='CalibrationTest',
        ),
        migrations.DeleteModel(
            name='ToolEquipment',
        ),
    ]
