# Generated by Django 5.1.4 on 2025-01-11 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vda', '0002_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('VDA', 'Vehicle Damage Assessor'), ('PNL', 'Panel Technician'), ('MET', 'Mechanical & Electrical Technician'), ('PNT', 'Paint Technician')], max_length=3)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='vda.client')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='vda.staff')),
            ],
        ),
    ]
