# Generated by Django 5.1.5 on 2025-01-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vda', '0003_remove_toolequipment_client_delete_calibrationtest_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
