# Generated by Django 5.1.5 on 2025-01-18 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_alter_user_client'),
        ('documents', '0002_alter_document_client'),
        ('staff', '0002_alter_job_client_alter_staff_client'),
        ('tools', '0002_alter_calibrationtest_client_and_more'),
        ('vda', '0004_delete_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
