# Generated by Django 5.1.4 on 2025-01-12 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vda', '0005_toolequipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('test_completion_date', models.DateField()),
                ('test_renewal_date', models.DateField()),
                ('test_score', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='vda.client')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='vda.toolequipment')),
            ],
        ),
    ]
