# Generated by Django 5.1.4 on 2025-01-12 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vda', '0006_calibrationtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('REPAIR_PROCESS', '4.0 Repair Process'), ('PEOPLE_PROCESSES', '4.4 People Processes'), ('REPAIR_METHODS', '4.5 Repair Methods'), ('EQUIPMENT_TOOLS', '4.6 Equipment & Tools'), ('PARTS_CONSUMABLES', '4.7 Parts & Consumables'), ('REPAIR_TASK_CONTROL', '4.8 Repair Task Control'), ('SUBCONTRACTORS', '4.9 Use of Subcontractors'), ('PROCESS_MANAGEMENT', '5.0 Process Management'), ('CLAIMS_CONFORMITY', '6.0 Claims of Conformity'), ('CUSTOMER_COMPLAINTS', '7.0 Customer Complaints'), ('INTERNAL_AUDIT_REPORTS', 'Internal Audit & Reports')], max_length=50, unique=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/documents/')),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vda.client')),
            ],
        ),
    ]
