# Generated by Django 5.1.5 on 2025-01-22 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Job',
            new_name='StaffJob',
        ),
        migrations.RenameModel(
            old_name='Qualification',
            new_name='StaffQualification',
        ),
        migrations.CreateModel(
            name='QualificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('jobtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.jobtypes')),
            ],
        ),
    ]
