# Generated by Django 5.1.5 on 2025-02-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_jobtypes_rename_job_staffjob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtypes',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='qualificationtype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
