# Generated by Django 5.1.5 on 2025-02-09 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_jobtypes_name_alter_qualificationtype_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffjob',
            name='role',
        ),
        migrations.AddField(
            model_name='staffjob',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='staff_jobs', to='staff.jobtypes'),
            preserve_default=False,
        ),
    ]
