# Generated by Django 5.1.5 on 2025-02-09 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_remove_staffjob_role_staffjob_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffjob',
            old_name='job',
            new_name='role',
        ),
    ]
