# Generated by Django 5.1.5 on 2025-02-09 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_rename_job_staffjob_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffjob',
            old_name='role',
            new_name='job',
        ),
    ]
