# Generated by Django 5.1.5 on 2025-02-10 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_rename_role_staffjob_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffqualification',
            name='qualification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='staff.qualificationtype'),
            preserve_default=False,
        ),
    ]
