# Generated by Django 5.1.5 on 2025-01-20 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools_equipment', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('test_completion_date', models.DateField()),
                ('test_renewal_date', models.DateField()),
                ('test_score', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='clients.client')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='tools.toolequipment')),
            ],
        ),
    ]
