# Generated by Django 5.1.5 on 2025-01-18 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationtest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='toolequipment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools_equipment', to='clients.client'),
        ),
    ]
